version: '3.7'
services:
  proxy:
    image: blockchain-proxy
    build:
      dockerfile: proxy/Dockerfile
      context: .
    environment:
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - HOME_CHAIN_ID
      - SIDE_RPC_URL
      - SIDE_SHARED_DB_ADDRESS
      - SIDE_CHAIN_ID
      - VALIDATOR_PRIVATE_KEY
      - FOREIGN_URL
      - FOREIGN_ASSET
      - 'LOG_LEVEL=info'
    volumes:
      - '../deploy/deploy-test/build/contracts/IERC20.json:/proxy/contracts_data/IERC20.json'
      - '../deploy/deploy-home/build/contracts/Bridge.json:/proxy/contracts_data/Bridge.json'
      - '../deploy/deploy-side/build/contracts/SharedDB.json:/proxy/contracts_data/SharedDB.json'
    ports:
      - '${VOTES_PROXY_PORT}:8002'
    networks:
      - test_network
      - blockchain_home
      - blockchain_side
  keygen:
    image: keygen-client
    build:
      dockerfile: tss-keygen/Dockerfile
      context: .
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
      - 'LOG_LEVEL=info'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    networks:
      - test_network
  signer:
    image: sign-client
    build:
      dockerfile: tss-sign/Dockerfile
      context: .
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
      - FOREIGN_CHAIN_ID
      - FOREIGN_URL
      - FOREIGN_ASSET
      - 'LOG_LEVEL=info'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    ports:
      - '${SIGN_RESTART_PORT}:8001'
    networks:
      - test_network
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - '${PWD}/${TARGET_NETWORK}/db:/data'
    networks:
      - test_network
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    environment:
      RABBITMQ_LOGS: 'false'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/queue:/var/lib/rabbitmq/mnesia'
    networks:
      - test_network
  eth-watcher:
    build:
      dockerfile: ethWatcher/Dockerfile
      context: .
    image: eth-watcher
    environment:
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - HOME_CHAIN_ID
      - HOME_START_BLOCK
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'LOG_LEVEL=info'
    volumes:
      - '../deploy/deploy-home/build/contracts/Bridge.json:/watcher/contracts_data/Bridge.json'
      - '../deploy/deploy-test/build/contracts/IERC20.json:/watcher/contracts_data/IERC20.json'
    networks:
      - test_network
      - blockchain_home
  bnc-watcher:
    build:
      dockerfile: bncWatcher/Dockerfile
      context: .
    image: bnc-watcher
    environment:
      - FOREIGN_URL
      - FOREIGN_ASSET
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
      - 'LOG_LEVEL=info'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    networks:
      - test_network
networks:
  test_network:
  blockchain_side:
    external: true
  blockchain_home:
    external: true
