version: '3.7'
services:
  proxy:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - HOME_CHAIN_ID
      - SIDE_RPC_URL
      - SIDE_SHARED_DB_ADDRESS
      - SIDE_CHAIN_ID
      - VALIDATOR_PRIVATE_KEY
      - FOREIGN_URL
      - FOREIGN_ASSET
    volumes:
      - '../deploy/deploy-test/build/contracts/IERC20.json:/proxy/contracts_data/IERC20.json'
      - '../deploy/deploy-home/build/contracts/Bridge.json:/proxy/contracts_data/Bridge.json'
      - '../deploy/deploy-side/build/contracts/SharedDB.json:/proxy/contracts_data/SharedDB.json'
    ports:
      - '${VOTES_PROXY_PORT}:8002'
    networks:
      - sign-proxy-net
      - keygen-proxy-net
      - bncwatcher-proxy-net
  keygen:
    image: keygen-client
    build: ./tss-keygen
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    networks:
      - keygen-proxy-net
      - rabbit-keygen-net
      - redis-keygen-net
  signer:
    image: sign-client
    build: ./tss-sign
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
      - FOREIGN_CHAIN_ID
      - FOREIGN_URL
      - FOREIGN_ASSET
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    ports:
      - '${SIGN_RESTART_PORT}:8001'
    networks:
      - sign-proxy-net
      - rabbit-signer-net
      - redis-signer-net
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - '${PWD}/${TARGET_NETWORK}/db:/data'
    networks:
      - redis-signer-net
      - redis-keygen-net
      - redis-ethwatcher-net
      - redis-bncwatcher-net
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    environment:
      RABBITMQ_LOGS: 'false'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/queue:/var/lib/rabbitmq/mnesia'
    networks:
      - rabbit-signer-net
      - rabbit-keygen-net
      - rabbit-ethwatcher-net
      - rabbit-bncwatcher-net
  eth-watcher:
    build: ethWatcher
    image: eth-watcher
    environment:
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - HOME_CHAIN_ID
      - HOME_START_BLOCK
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
    volumes:
      - '../deploy/deploy-home/build/contracts/Bridge.json:/watcher/contracts_data/Bridge.json'
      - '../deploy/deploy-test/build/contracts/IERC20.json:/watcher/contracts_data/IERC20.json'
    networks:
      - rabbit-ethwatcher-net
      - redis-ethwatcher-net
  bnc-watcher:
    build: bncWatcher
    image: bnc-watcher
    environment:
      - FOREIGN_URL
      - FOREIGN_ASSET
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    networks:
      - rabbit-bncwatcher-net
      - redis-bncwatcher-net
      - bncwatcher-proxy-net
networks:
  sign-proxy-net:
  keygen-proxy-net:
  rabbit-signer-net:
  rabbit-keygen-net:
  rabbit-ethwatcher-net:
  rabbit-bncwatcher-net:
  redis-keygen-net:
  redis-signer-net:
  redis-ethwatcher-net:
  redis-bncwatcher-net:
  bncwatcher-proxy-net:
