version: '3.7'
services:
  proxy:
    image: blockchain-proxy
    build:
      dockerfile: proxy/Dockerfile
      context: .
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - SIDE_RPC_URL
      - SIDE_SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY
      - FOREIGN_URL
      - FOREIGN_ASSET
      - LOG_LEVEL
    ports:
      - '${VOTES_PROXY_PORT}:8002'
    networks:
      test_network:
        aliases:
          - local_proxy
      ethereum_home_rpc_net:
      ethereum_side_rpc_net:
      binance_net:
  keygen:
    image: keygen-client
    build:
      dockerfile: tss-keygen/Dockerfile
      context: .
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://local_proxy:8001'
      - KEYGEN_ATTEMPT_TIMEOUT
      - KEYGEN_EPOCH_CHECK_INTERVAL
      - LOG_LEVEL
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    ports:
      - '${KEYGEN_RESTART_PORT}:8001'
    networks:
      - test_network
  signer:
    image: sign-client
    build:
      dockerfile: tss-sign/Dockerfile
      context: .
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://local_proxy:8001'
      - FOREIGN_CHAIN_ID
      - FOREIGN_URL
      - FOREIGN_ASSET
      - SIGN_ATTEMPT_TIMEOUT
      - SIGN_NONCE_CHECK_INTERVAL
      - SEND_TIMEOUT
      - LOG_LEVEL
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    ports:
      - '${SIGN_RESTART_PORT}:8001'
    networks:
      - test_network
      - binance_net
  redis:
    image: redis
    build:
      dockerfile: redis/Dockerfile
      context: .
    volumes:
      - '${PWD}/${TARGET_NETWORK}/db:/data'
    networks:
      - test_network
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    environment:
      RABBITMQ_LOGS: 'false'
    volumes:
      - '${PWD}/${TARGET_NETWORK}/queue:/var/lib/rabbitmq/mnesia'
    networks:
      - test_network
  eth-watcher:
    build:
      dockerfile: ethWatcher/Dockerfile
      context: .
    image: eth-watcher
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'REDIS_HOST=redis'
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - HOME_TOKEN_ADDRESS
      - HOME_START_BLOCK
      - VALIDATOR_PRIVATE_KEY
      - HOME_MAX_FETCH_RANGE_SIZE
      - LOG_LEVEL
    networks:
      - test_network
      - ethereum_home_rpc_net
  bnc-watcher:
    build:
      dockerfile: bncWatcher/Dockerfile
      context: .
    image: bnc-watcher
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://local_proxy:8001'
      - 'REDIS_HOST=redis'
      - FOREIGN_URL
      - FOREIGN_ASSET
      - FOREIGN_FETCH_MAX_TIME_INTERVAL
      - FOREIGN_FETCH_INTERVAL
      - FOREIGN_FETCH_BLOCK_TIME_OFFSET
      - LOG_LEVEL
    volumes:
      - '${PWD}/${TARGET_NETWORK}/keys:/keys'
    networks:
      - test_network
      - binance_net
  side-watcher:
    build:
      dockerfile: sideWatcher/Dockerfile
      context: .
    image: side-watcher
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'REDIS_HOST=redis'
      - HOME_RPC_URL
      - HOME_BRIDGE_ADDRESS
      - SIDE_RPC_URL
      - SIDE_START_BLOCK
      - SIDE_MAX_FETCH_RANGE_SIZE
      - SIDE_SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY
      - LOG_LEVEL
    networks:
      - test_network
      - ethereum_home_rpc_net
      - ethereum_side_rpc_net
  home-sender:
    build:
      dockerfile: ethSender/Dockerfile
      context: .
    image: sender
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'RPC_URL=${HOME_RPC_URL}'
      - 'TO_ADDRESS=${HOME_BRIDGE_ADDRESS}'
      - 'GAS_LIMIT_FACTOR=3'
      - 'MAX_GAS_LIMIT=6000000'
      - 'QUEUE_NAME=homeSendQueue'
      - VALIDATOR_PRIVATE_KEY
      - LOG_LEVEL
    networks:
      test_network:
        aliases:
          - local_home-sender
      ethereum_home_rpc_net:
  side-sender:
    build:
      dockerfile: ethSender/Dockerfile
      context: .
    image: sender
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'RPC_URL=${SIDE_RPC_URL}'
      - 'TO_ADDRESS=${SIDE_SHARED_DB_ADDRESS}'
      - 'GAS_LIMIT_FACTOR=3'
      - 'MAX_GAS_LIMIT=6000000'
      - 'QUEUE_NAME=sideSendQueue'
      - VALIDATOR_PRIVATE_KEY
      - LOG_LEVEL
    networks:
      - test_network
      - ethereum_side_rpc_net
networks:
  test_network:
  ethereum_side_rpc_net:
    external: true
  ethereum_home_rpc_net:
    external: true
  binance_net:
    external: true
