version: '3.7'
services:
  proxy:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - sign-proxy-net
      - keygen-proxy-net
  keygen:
    image: keygen-client
    build: ./tss-keygen
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
    volumes:
      - '${PWD}/keys:/keys'
    networks:
      - keygen-proxy-net
      - rabbit-keygen-net
      - redis-keygen-net
  signer:
    image: sign-client
    build: ./tss-sign
    environment:
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
      - 'PROXY_URL=http://proxy:8001'
      - FOREIGN_CHAIN_ID
      - FOREIGN_URL
    volumes:
      - '${PWD}/keys:/keys'
    networks:
      - sign-proxy-net
      - rabbit-signer-net
      - redis-signer-net
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - '${PWD}/db:/data'
    networks:
      - redis-signer-net
      - redis-keygen-net
      - redis-watcher-net
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    volumes:
      - '${PWD}/queue:/var/lib/rabbitmq/mnesia'
    networks:
      - rabbit-signer-net
      - rabbit-keygen-net
      - rabbit-watcher-net
  eth-watcher:
    build: ./watcher
    image: eth-watcher
    environment:
      - 'HOME_RPC_URL=${RPC_URL}'
      - 'HOME_BRIDGE_ADDRESS=${SHARED_DB_ADDRESS}'
      - 'RABBITMQ_URL=amqp://rabbitmq:5672'
    volumes:
      - '../deploy/build/contracts:/watcher/contracts_data'
    networks:
      - rabbit-watcher-net
      - redis-watcher-net
networks:
  sign-proxy-net:
  keygen-proxy-net:
  rabbit-signer-net:
  rabbit-keygen-net:
  rabbit-watcher-net:
  redis-keygen-net:
  redis-signer-net:
  redis-watcher-net:
