version: '3.7'
services:
  proxy1:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=e2c1349f1d13f22cd011a9cfef7007388b8df16a6e1f318517cb93dbadcd9c2e
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net1
  proxy2:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=7562a3ea655c2aad92a819069d334e7cf6edc9d2ae0fcc9a6498bd38842fafd4
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net2
  proxy3:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=955b1f58a207160459e3be344e8a9cae2c3db47a0cb8275eb771a51da84de244
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net3
  proxy4:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=a1c08300192fdd27aa92cd836ca98601c35184319c6873b1d1478f21cdb1c867
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net4
  proxy5:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=3aef900c61246653308ed0770f3bd67a1c21342cf2a7dbf0ee5bcc787b627de0
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net5
  proxy6:
    image: blockchain-proxy
    build: ./proxy
    environment:
      - RPC_URL
      - SHARED_DB_ADDRESS
      - VALIDATOR_PRIVATE_KEY=abe7f999209549463e7da719eddd6bb3e00fe77832f5166c1e57d067452954b6
    volumes:
      - '../deploy/build/contracts:/proxy/contracts_data'
    networks:
      - keygen-proxy-net6
  keygen1:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy1:8001'
    volumes:
      - './keys1.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net1
  keygen2:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy2:8001'
    volumes:
      - './keys2.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net2
  keygen3:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy3:8001'
    volumes:
      - './keys3.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net3
  keygen4:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy4:8001'
    environment:
      - SKIP_SIGN=true
    volumes:
      - './keys4.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net4
  keygen5:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy5:8001'
    environment:
      - SKIP_SIGN=true
    volumes:
      - './keys5.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net5
  keygen6:
    image: keygen-client
    build: ./tss-keygen
    command: 'http://proxy6:8001'
    environment:
      - SKIP_SIGN=true
    volumes:
      - './keys6.store:/tss/keys.store'
      - './params:/tss/params'
    networks:
      - keygen-proxy-net6
networks:
  keygen-proxy-net1:
  keygen-proxy-net2:
  keygen-proxy-net3:
  keygen-proxy-net4:
  keygen-proxy-net5:
  keygen-proxy-net6:
