version: 2.1
orbs:
  bridge:
    executors:
      node-dev:
        docker:
          - image: circleci/node:10.15
        environment:
          TARGET_NETWORK: development
jobs:
  init_tss:
    executor: bridge/node-dev
    steps:
      - checkout
      - run: git submodule update --init
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: docker build -t tss ./src/tss
      - run: mkdir ./workspace
      - run: docker save tss | gzip ./workspace/tss.tar.gz
      - persist_to_workspace:
          root: ./workspace
          paths:
            - tss.tar.gz

  init_blockchains:
    executor: bridge/node-dev
    steps:
      - checkout
      - run: git submodule update --init
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: ./demo/start-environment.sh
      - run: touch ./src/test-services/.keys.$TARGET_NETWORK
      - run: ./src/test-services/ethereumSend/run.sh 0x4db6b4bd0a3fdc03b027a60f1c48f05c572312aa 100
      - run: ./src/test-services/ethereumSend/run.sh 0xf7ca4aed1795e424433498cef43f6a3825c88731 100
      - run: ./src/test-services/ethereumSend/run.sh 0xad6c8127143032d843a260c5d379d8d9b3d51f15 100
      - run: docker kill ganache_side ganache_home
      - run: docker run --rm -v "ganache_side_data:/ganache_side_data" -v "ganache_home_data:/ganache_home_data" -d --name tmp alpine:3.9.4
      - run: mkdir ./workspace
      - run: docker cp "tmp:/ganache_side_data" "./workspace/ganache_side_data"
      - run: docker cp "tmp:/ganache_home_data" "./workspace/ganache_home_data"
      - run: docker kill tmp
      - persist_to_workspace:
          root: ./workspace
          paths:
              - ganache_side_data
              - ganache_home_data

  run_tests:
    executor: bridge/node-dev
    steps:
      - checkout
      - run: git submodule update --init
      - attach_workspace:
          at: ./workspace
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: docker load -i ./workspace/tss.tar.gz
      - run: docker images
      - run: docker volume create ganache_side_data
      - run: docker volume create ganache_home_data
      - run: docker run --rm -v "ganache_side_data:/ganache_side_data" -v "ganache_home_data:/ganache_home_data" -d --name tmp alpine:3.9.4
      - run: docker cp "./workspace/ganache_side_data" "tmp:/ganache_side_data"
      - run: docker cp "./workspace/ganache_home_data" "tmp:/ganache_home_data"
      - run: docker kill tmp
      - run:
          command: ./tests/init.sh
          environment:
            HOME_RPC_URL: 'http://ganache_home:8545'
workflows:
  version: 2
  main:
    jobs:
      - init_tss
      - init_blockchains
      - run_tests:
          requires:
            - init_tss
            - init_blockchains
