version: 2.1
orbs:
  bridge:
    executors:
      node:
        docker:
          - image: circleci/node:10.15
    commands:
      fetch_repo:
        description: "Checkout and init submodules"
        steps:
          - checkout
          - run:
              name: "Initialize submodules"
              command: git submodule update --init
      install_truffle_ganache:
        description: "Install truffle and ganache-cli"
        steps:
          - run:
              name: "Install truffle"
              command: npm install -g truffle@v5.0.39
          - run:
              name: "Install ganache-cli"
              command: npm install -g ganache-cli@v6.4.4
      install_linters:
        description: "Install code linters"
        steps:
          - run:
              name: "Install eslint"
              command: npm install -g eslint@v6.6.0
          - run:
              name: "Install solhint"
              command: npm install -g solhint@2.3.0
      setup_docker:
        description: "Set up remote docker engine"
        steps:
          - setup_remote_docker:
              version: 18.09.3
              docker_layer_caching: true
      save_tss:
        description: "Save tss image to workspace"
        steps:
          - run:
              name: "Save tss image to archive"
              command: |
                mkdir -p ./workspace
                docker save tss | gzip > ./workspace/tss.tar.gz
          - persist_to_workspace:
              name: "Save tss image to workspace"
              root: ./workspace
              paths:
                - tss.tar.gz
      load_tss:
        description: "Load tss image from workspace"
        steps:
          - run:
              name: "Load tss image from archive"
              command: docker load -i ./workspace/tss.tar.gz || true
      save_docker_logs:
        description: "Save docker logs"
        parameters:
          validator:
            type: integer
            default: 1
        steps:
          - run:
              name: "Saving validator<< parameters.validator >> logs"
              command: |
                mkdir -p ./artifacts/logs/validator<< parameters.validator >>
                docker logs validator<< parameters.validator >>_rabbitmq_1 > ./artifacts/logs/validator<< parameters.validator >>/rabbitmq.log
                docker logs validator<< parameters.validator >>_redis_1 > ./artifacts/logs/validator<< parameters.validator >>/redis.log
                docker logs validator<< parameters.validator >>_proxy_1 > ./artifacts/logs/validator<< parameters.validator >>/proxy.log
                docker logs validator<< parameters.validator >>_eth-watcher_1 > ./artifacts/logs/validator<< parameters.validator >>/eth-watcher.log
                docker logs validator<< parameters.validator >>_bnc-watcher_1 > ./artifacts/logs/validator<< parameters.validator >>/bnc-watcher.log
                docker logs validator<< parameters.validator >>_signer_1 > ./artifacts/logs/validator<< parameters.validator >>/signer.log
                docker logs validator<< parameters.validator >>_keygen_1 > ./artifacts/logs/validator<< parameters.validator >>/keygen.log
                docker logs validator<< parameters.validator >>_side-watcher_1 > ./artifacts/logs/validator<< parameters.validator >>/side-watcher.log
                docker logs validator<< parameters.validator >>_side-sender_1 > ./artifacts/logs/validator<< parameters.validator >>/side-sender.log
                docker logs validator<< parameters.validator >>_home-sender_1 > ./artifacts/logs/validator<< parameters.validator >>/home-sender.log
              when: always
      save_artifacts:
        description: "Save and upload tests results, save validator logs to artifacts"
        steps:
          - run:
              name: "Save tests results"
              command: |
                mkdir -p ./artifacts/test_results/mocha
                cp "./tests/results.xml" "./artifacts/test_results/mocha/results.xml"
              when: always
          - store_test_results:
              path: ./artifacts/test_results/mocha
              when: always
          - save_docker_logs:
              validator: 1
          - save_docker_logs:
              validator: 2
          - save_docker_logs:
              validator: 3
          - run:
              name: "Save ethereum logs"
              command: |
                mkdir -p ./artifacts/logs/ethereum
                docker logs ethereum-testnet_ganache_home_1 > ./artifacts/logs/ethereum/ganache_home.log
                docker logs ethereum-testnet_ganache_side_1 > ./artifacts/logs/ethereum/ganache_side.log
              when: always
          - run:
              name: "Save binance logs"
              command: |
                mkdir -p ./artifacts/logs/binance
                docker logs binance-testnet_node_1 > ./artifacts/logs/binance/node.log
                docker logs binance-testnet_api-server_1 > ./artifacts/logs/binance/api-server.log
                docker logs binance-testnet_http-api_1 > ./artifacts/logs/binance/http-api.log
              when: always
          - store_artifacts:
              path: ./artifacts
              destination: artifacts
              when: always
jobs:
  init_tss:
    executor: bridge/node
    steps:
      - bridge/fetch_repo
      - bridge/setup_docker
      - run:
          name: "Build tss image"
          command: docker build -t tss ./src/tss
      - bridge/save_tss
  tests_e2e:
    executor: bridge/node
    steps:
      - bridge/fetch_repo
      - bridge/setup_docker
      - attach_workspace:
          at: ./workspace
      - bridge/load_tss
      - run: npm run tests:e2e
      - run:
          name: "Check alive docker containers"
          command: docker ps
          when: always
      - bridge/save_artifacts
  lint:
    executor: bridge/node
    steps:
      - bridge/fetch_repo
      - bridge/install_linters
      - run: npm run lint
  tests_home:
    executor: bridge/node
    steps:
      - bridge/fetch_repo
      - bridge/install_truffle_ganache
      - run:
          name: "Install test dependencies"
          command: |
            cd ./src/contracts/home
            npm install
      - run: npm run tests:home
  tests_side:
    executor: bridge/node
    steps:
      - bridge/fetch_repo
      - bridge/install_truffle_ganache
      - run:
          name: "Install test dependencies"
          command: |
            cd ./src/contracts/side
            npm install
      - run: npm run tests:side
workflows:
  version: 2
  main:
    jobs:
      - lint
      - init_tss
      - tests_e2e:
          requires:
            - init_tss
      - tests_home
      - tests_side
