version: '3.0'
services:
  testnet:
    build: ./testnet
    image: bnc-testnet
    networks:
      - binance_rpc_net
    volumes:
      - 'marketdata:/root/.bnbchaind/marketdata'
  api-server:
    build: ./api-server
    image: bnc-api-server
    networks:
      - binance_net
      - binance_rpc_net
    ports:
      - '8000:8000'
    volumes:
      - 'marketdata:/api-server/marketdata'
networks:
  binance_net:
    external: true
  binance_rpc_net:
volumes:
  marketdata:
