[development]
address = "127.0.0.1"
port = 8001
workers = 12
keep_alive = 5
log = "normal"

[staging]
address = "0.0.0.0"
port = 8001
workers = 8
keep_alive = 5
log = "normal"
secret_key = "nSLM0D9ip+Gb1DNAOOisC9I+xLYHueO6FhtrNJwCRhE="

[production]
address = "0.0.0.0"
port = 8001
workers = 1
keep_alive = 5
log = "critical"
secret_key = "VWLeaDIng4S6bpN+Lgey5BbYwAZ3hM1hKzuMCWvEqVo="
